<?php
namespace app\index\controller;


class About extends  \app\common\controller\Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return $this->fetch();
    }
}
